name: Update Telegram Images

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

permissions:
  contents: write  # 🔐 Required for push access

jobs:
  update-backgrounds:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run background fetch script
        run: python telegram/telegram_scripts/fetch_telegram_images.py

      - name: Commit and push updates if needed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add backgrounds.json images/

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update background images from Telegram"
            git push
          fi
