name: Update Telegram Images

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

permissions:
  contents: write      # required to push changes
  pages: write         # required to trigger Pages deployment
  id-token: write      # required for OIDC authentication

jobs:
  update-channel-images:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run channel image fetch script
        run: python telegram/telegram_scripts/fetch_telegram_images.py

      - name: Commit and push updates if needed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add telegram/telegram_images/channel_images.json telegram/telegram_images/

          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "Update channel images from Telegram"
            git push
            echo "✅ Changes pushed, triggering GitHub Pages build"
          fi
